---
 
  - name: Package update  
    yum: 
        name:     "{{ package_name }}"
        state:    "{{ package_state }}"
        security: "{{ security_only_required }}"
    notify:
           - Server reboot if needed...

...           
